:PROPERTIES:
:ID: 75636812-AD96-4DE2-B482-288DEA167BD7
:END:
#+title: college-journal-11

/Journal 11th Grade

Who are you from?
where do you get info?
what are your challenges/trimphes\\
insight into your goals hopes and fears\\

10/6/21 Entry 2\\
What I saw was waking up at 6am going for a run with the other cadets. Going to class and studying in between ROTC events. The dorms would be the bericks. I envisioned a difficult experience that would challenge me. These visions are comming from my own imagination and the talks I have done with people who go there. I have been to other colleges but those don't seem appealing to me as that is not what I want in a college experience.\\

10/19/21 Entry 3\\
What is your favorite class this year so far? Why is it your favorite? Has your favorite subject changed from year to year or remained fairly constant?\\

My favorite class this year has been math because I have been looking forward to calculus for a long time because it has been hyped up to be some big fish by my parents. However, I have found it very enjoyable. I think this has remained extremely consistent over the years but this year I have come to like it more. I really want to pursue higher levels of math in senior year. I am very sure that I would want to major in computer science with wither a minor or double major in mathematics. I think I am ready to specialize in the sence that I am ready to commit to it but I am undecided if I want to double major.\\

10/28/21 Entry 4\\
What are your current evolvement?\\

Math Club, NLYM, Track and Feild, CS club, Boy Scouts,\\

clubs: computor science club, rock climbing club, esports club, virtually
reality club, tennis club, tedx-smu

12/13/21 Entry 5

Journal Prompt: Are you open to going to college in the northeast US? The
southeast? The midwest? The southern US? The northwest US? The southwest US?
In California? Outside the US? Are your geographic preferences based on
experience, reputation, weather, proximity to or distance from family?

I think I am open to going to college mostly anywhere but weather is always
something I have to think about.

Please elaborate on your YES or NO answers to these questions to help me get a
better sense of what you're thinking about this aspect of your college process.

What is your plan for standardized testing? Which tests will you take and
when? How will you prepare? Are you happy with any scores you already have?
Are you interested in learning more about test optional colleges?

My plan for standardized testing is to prepare with a book I bought. I am only
concerned about the English Section and I think I will be ok on the two math
ones. I plan to take the tests in the spring. I did not know that test optional
schools existed before this question.
