:PROPERTIES:
:ID: 7A890597-1811-46C0-B262-CFEA4DC5A5F9
:END:
#+title: The Big Sleep (Book)

Evan Stokdyk
9/3/22
Mr. Levine
English - Block 4

What does the environment in chapter 6 suggest or reveal?

In chapter 6 of Raymond Chandler's The Big Sleep, the water and by extension the rain alongside the background characteristics of the scenes help to frame the emotions of Phillip Marlowe and themes of story moments. The nature of mystery novels involves implying things to the reader and this chapter uses the rainy weather and its consequences to signify mounting complexity. At the start of the chapter, Phillip Marlowe sits in his car and describes his situation as he waits for something: “The rain drummed hard on the roof of the car and the burbank top began to leak. A pool of water formed on the floorboards for me to keep my feet in” (Chandler 30). The imagery of rain piercing through the normally protective barrier shows how with each chapter's observation this simple case introduced at the start of the book gains more mystery. Secondly, the fact that Marlowe seems to show apathy towards a frustrating situation of the invasive rain shows his enjoyment for puzzles. On a surface level, it is uncommon for people to want to marinate their own feet so Marlowe's half full perspective on the water, significant of mystery, shows that even if the case that he was hired for is more complicated than he expected, that is ok. Next, scenery is used to tell the reader about the mood of a scene. While Marlowe is parked outside of a house, the reader is given very little description into what is happening inside the house: “Their front windows were masked by hedges and shrubs. Sodden trees dripped all over the landscape” (Chandler 32). This description of the outside environment of the house helps to show by proxy what is happening in the house. The imagery of a mask further pushes the unknown of this scene as all we are shown is a normal looking mask that conceals the sinister of the house. In addition, the implication that water stood for mystery in the last quote reveals that this scene adds further complexity to Marlowe's job. Without being told or being a good detective the reader can deduce that this house is not as it seems and that it is important to the rising action of this book. Overall, in a book where nothing can be outright stated, the weather and environment help to guide the reader to understanding the mood, significance and meaning of scenes and characters.
