:PROPERTIES:
:ID: F670E998-C1C1-43E1-8C58-934D9EB2709C
:END:
#+title: csci108-hw2

Evan Stokdyk

CSCI 163 - WINTER 2025

Assignment 2

* Problem 1
Solve the following recurrence equation to get a closed-formula for \(T(n)\) using backward substitution. You may assume that n is a power of 3.

\(T(n) = 1; n = 1\)
\(T(n) = 9T ( \frac{n}{3} ) + n; n ≥ 2\)

#+begin_quote
[!tip] Proof
Let m be the number such that \(n=3^m\). 1) \(T(n) = 9T(\frac{n}{3}) + n\) 2) \(T(n) = 3^2T(3^{m-1}) + 3^m\) 3) \(T(n) = 3^2(3^2T(3^{m-2}) + 3^{m-1} ) + 3^m\) 4) \(T(n) = 3^4T(3^{m-2}) + 3^{m+1} + 3^m\) 5) \(T(n) = 3^6T(3^{m-3}) + 3^{m+2} + 3^{m+1} + 3^m\) 5) \(...\) 6) \(T(n) = 3^{2k}T(3^{m-k}) + 3^{m+k-1} + ... + 3^{m+1} + 3^m\) 6) \(...\) 7) \(T(n) = 3^{2m}T(0) + 3^{m+m-1} + ... + 3^{m+1} + 3^m\) 8) \(T(n) = 3^{2m} + 3^{2m-1} + ... + 3^{m+1} + 3^m\) 8) \(T(n) = 3^{m}(\frac{1-3^{m+1}}{1-3})\) 8) \(T(n) = \frac{3^{m}-3^{2m+1}}{-2}\) 8) \(T(n) = \frac{1}{2}(3^{2m+1} - 3^{m})\) 8) \(T(n) = \frac{3}{2}n^2 - \frac{n}{2}\)

* Problem 2
Consider the following recursive algorithm.

#+begin_example
//ALGORITHM Q(n)
//Input: A positive integer n
If n = 1, return 1
else return Q(n − 1) + 3n + 2
#+end_example
#+end_quote

** Part A
Set up a recurrence relation for the function's values and solve it to determine what this algorithm computes.

#+begin_quote
[!tip] Proof 1) \(Q(1)=1\) 2) \(Q(n)=Q(n-1)+3n+2\) 3) \(Q(n)=Q(n-2)+3(n-1)+2+3n+2\) 4) \(Q(n)=Q(n-2)+3n-3+2+3n+2\) 5) \(Q(n)=Q(n-2)+6n+2(2)-3(1+0)\) 6) \(Q(n)=Q(n-3)+3(n-2)+2+6n+2(2)-3(1+0)\) 7) \(Q(n)=Q(n-3)+9n+3(2)-3(2+1+0)\) 8) \(Q(n)=Q(n-4)+12n+4(2)-3(3+2+1+0)\) 9) \(Q(n)=Q(n-k)+3kn+k(2)-3((k-1)+(k-2)+...+1+0)\) 10) \(Q(n)=Q(n-(n-1))+3(n-1)n+(n-1)(2)-3((n-2)+(n-3)+...+1+0)\) 11) \(Q(n)=Q(1)+3n^2-3n+2n-2-3(\frac{(n-1)(n-2)}{2})\) 12) \(Q(n)=Q(1)+3n^2-n-2-3(\frac{n^2-3n+2}{2})\) 13) \(Q(n)=1+(3-\frac{3}{2})n^2+(\frac{9}{2}-1)n-5\) 14) \(Q(n)=\frac{3}{2}n^2+\frac{7}{2}n-4\)
#+end_quote

** Part B
Set up a recurrence relation for the number of multiplications made by this algorithm and solve it.

#+begin_quote
[!tip] Proof 1) \(M(1)=0\) 2) \(M(n)=M(n-1)+1\) 3) \(M(n)=M(n-2)+1+1\) 4) \(M(n)=M(n-k)+k\) 5) \(M(n)=M(n-(n-1))+(n-1)\) 6) \(M(n)=0+n-1\) 7) \(M(n)=n-1\)
#+end_quote

** Part C
Set up a recurrence relation for the number of additions and subtractions made by this algorithm outside the recursive call and solve it.

#+begin_quote
[!tip] Proof 1) \(A(1)=0\) 2) \(A(n)=A(n-1)+2\) 3) \(A(n)=A(n-2)+2+2\) 4) \(A(n)=A(n-k)+2k\) 5) \(A(n)=A(n-(n-1))+2(n-1)\) 6) \(A(n)=0+2n-2\) 7) \(A(n)=2n-2\)
#+end_quote

* Problem 3
Solve the following recurrence equations using the Master Theorem.
​## Part A
Given: \(T(n) = 16T (n/4) + n^4\)
> [!tip] Proof
> 1) \(a=16, b=4, f(n)=n^4\)
> 2) \(c_{crit}=\log_4 16=2\)
> 3) \(f(n)=\Omega(n^c); c=4\)
> 4) \(c>c_{crit};\) therefore case 3
> 5) \(T(n)=\Theta(f(n))=\Theta(n^4)\)

** Part B
Given: \(T (n) = 125T (n/5) + 9^{\log_3 n}\)
> [!tip] Proof
> 1) \(a=125; b=5; f(n)=9^{\log_3 n}\)
> 2) \(c_{crit}=\log_5 125=3\)
> 3) \(f(n)=9^{\log_3 n}=3^{2\log_3 n}=(3^{\log_3 n})^2=n^2=\Theta(n^c); c=2\)
> 4) \(c<c_{crit};\) therefore case 1
> 5) \(T(n)=\Theta(n^{c_{crit}})=\Theta(n^3)\)

** Part C
Given: \(T (n) = 64T (n/8) + n^2\)
> [!tip] Proof
> 1) \(a=64; b=8; f(n)=n^2\)
> 2) \(c_{crit}=\log_8 64=2\)
> 3) \(f(n)=n^c; c=2=c_{crit};\) therefore case 2
> 2) \(f(n)=\Theta(n^{2}\log^k n);k=0\)
> 5) \(T(n)=\Theta(n^{c_{crit}}\log^{k+1}n)=\Theta(n^2\log^{0+1} n)\)
> 5) \(T(n)=\Theta(n^2\log n)\)
