:PROPERTIES:
:ID: 1AD81D3D-5B33-4224-A97A-EAEB5FA4F845
:END:
#+title: csci163-hw7

Evan Stokdyk

CSCI 163 - WINTER 2025

Assignment 7

* Problem 1

#+begin_quote
[!faq] Problem
If all the edge weights in a weighted, undirected graph are distinct, show that its MST is unique.
#+end_quote

#+begin_quote
[!qna] Proof
There exists an trival unique MST for a graph with 1 node. Consider adding a new node to that graph. There are either 1 or more connections to the current MST. If there is only 1 then that is the only choice and so the solution remains unique. If there is more than one option one must have the lowest value as all are distinct. Therefore, there remains only one solution. By induction, for any size graph there must be a unique MST.
#+end_quote

* Problem 2

#+begin_quote
[!faq] Problem
Show that for any vertex v, the lightest edge (aka edge of minimum weight) incident on v belongs to the MST. You can assume that all edge weights are distinct.
#+end_quote

#+begin_quote
[!qna] Proof
Consider a graph G. Consider the graph G[-v] which is the graph minus the node v. This graph is may not be connected but will always be exactly 1 or 2 connected graphs which both have an MST. To make a MST of G, if G[-v] is split then the node v must contain at least 1 edge to each graph. The minimum of each value set of edges that connect to each must be selected. One of the minimum of each set must be the minimum of their union so the lightest edge must be included in the MST. If G[-v] is already a connected graph then by the same logic in problem 1, the lightest edge must be included.
#+end_quote
