:PROPERTIES:
:ID: 2EC78C65-67E6-4F10-A1F1-358DCDD6E63C
:END:
#+title: ECEN50L-Lab6

--------------

title: "ECEN50L Th 2:15 - Lab 6: Storage Devices and RC Circuits"
author: "Evan Stokdyk"
date: "2025-05-29"
---

* Part 1 - Capacitors in Series
In this lab, we aims to see how well our model of voltage division for
capacitors in series is. We expect that the voltage will be divided at time 0
by the inverse of the capacitance, and then go to zero as time progresses.

First, we need to choose capcitors and resistors for this lab and see what they
measure at using the digital measuring device.

|                 | C1 (uF) | C2 (uF) | C3 (uF) |
|-----------------+---------+---------+---------|
| Nominal Values  | 1.0     | 2.2     | 4.7     |
| Measured Values | 1.09    | 2.32    | 5.22    |

#+begin_quote
Table 1.1 - Capacitance and Resistance Values
#+end_quote

|                 | R1 (Ohms) | R2 (Ohms) |
|-----------------+-----------+-----------|
| Nominal Values  | 500       | 750       |
| Measured Values | 499       | 749       |

#+begin_quote
Table 1.2 - Capacitance and Resistance Values
#+end_quote

Now we constructed a circuit with the 3 capcitors in series. We used matlab to
calculate the expected values using voltage division. We then measured to find
the values in lab. This builds the following table:

|     | Theoretical | Measured | Percent Error |
|-----+-------------+----------+---------------|
| V1  | 1.1914      | 1.136    | -4.65%        |
| V2  | 0.5598      | 0.571    | 2.00%         |
| V3  | 0.2488      | 0.244    | -1.92%        |
| Sum | 2           | 1.951    | -2.45%        |

#+begin_quote
Table 1.3 - Capacitor Voltage Measurements
#+end_quote

/If there are any discrepancies, explain. In particular, explain why the
percent error is likely to be negative./

The percent error is negative when there is excess charge in the capcitor due
to not being fully discharged. For V2 where the error is positive could be due
to the other capcitors not being discharged resulting in having a lower system
capacitance.

* Part 2 - RC Circuit
In this part, we will measure the time constant of an RC circuit using a few
different meathods. The circuit is constructed with a resitor and capcitors in
series.

First we, connected one channel of the oscilloscope to the source to measure
Vout for each of the frequencies 100, 200, 300, 400 and 500Hz. Frequencies
above 300Hz do not give the capacitor time to fully charge and discharge. For
this lab we will use 100Hz going forward for the least error.

Now, the oscillloscope was connected in parellel with the capcitors to produce
the following table:

| R   | t = RC  | t(+63.2%) | T(rise) | T(rise)/ln(9) | %Error |
|-----+---------+-----------+---------+---------------+--------|
| 499 | 543.9us | 572us     | 1.15ms  | 523us         | 5.16%  |
| 749 | 816.4us | 886us     | 1.67ms  | 760us         | 8.52%  |

| R   | t = RC  | t(-36.8%) | T(fall) | T(fall)/ln(9) | %Error |
|-----+---------+-----------+---------+---------------+--------|
| 499 | 543.9us | 564us     | 1.15ms  | 523us         | 3.75%  |
| 749 | 816.4us | 810us     | 1.67ms  | 760us         | -0.78% |

#+begin_quote
Table 2.1 - Time Constant Measurement Comparison
#+end_quote
