:PROPERTIES:
:ID: 2FFFE11C-2C34-4E9F-9033-93B9AF77BAF1
:END:
#+title: csci163-hw3

Evan Stokdyk

CSCI 163 - WINTER 2025

Assignment 3

* Problem 1

#+begin_quote
Design and analyze an exhaustive-search algorithm for the following problem:

INPUT: an array A[0, ... , n−1] of real values, and a target real value t

OUTPUT: TRUE iff there are three indices i < j < k such that \(A[i] + A[j] + A[k] = t\)
#+end_quote

** Answer
For exhaustive search, there would be three loop iterations each beginning at the previous value and would continue until a value is found, returning true otherwise.

Here is an example solution using the zig programming language:

#+begin_src zig
fn problem1(A: []f32, t: f32) bool {
    for (0..A.len - 2) |i|
        for (i + 1..A.len - 1) |j|
            for (j + 1..A.len) |k|
                if (A[i] + A[j] + A[k] == t) return true;
    return false;
}
#+end_src

* Problem 2

#+begin_quote
Design and analyze a decrease-conquer algorithm for the following problem:

INPUT: an array A[0, ... , n−1] of integers

OUTPUT: TRUE iff there are two indices i < j in A such that \(A[i] = A[j]\)
​## Answer
This problem can be solved using decrease-conquer by attempting to solve the list minus the first element. If that is true then returning true, otherwise comparing the first element to the tail of the list.
#+end_quote

Here is an example solution using zig:

#+begin_src zig
fn problem2(A: []usize) bool {
    if (A.len <= 1) return false;
    if (problem2(A[1..])) return true;
    for (A[1..]) |v|
        if (A[0] == v) return true;
    return false;
}
#+end_src

* Problem 3

#+begin_quote
Design faster algorithms for the two problems above.
​## Problem 1
The first algorithm walks the list three times in a loop so it has \(O(n^3)\) complexity. This is because each list item must be distinct so there are many checks needed. If the last loop is instead done using binary search then it takes \(\log n\) time which makes it overall \(O(n^2 \log n)\). Here is some example code:
#+end_quote

#+begin_src zig
fn problem1b(A: []f32, t: f32) bool {
    std.mem.sort(f32, A, {}, std.sort.asc(f32));
    for (A, 0..) |x, i| {
        for (A, 0..) |y, j| {
            if (i == j) continue;
            const target = t - (x + y);
            // if the index exists then seek start of duplicates
            var ind = std.sort.binarySearch(f32, target, A, {}, cmp.float) 
                orelse continue;
            while (ind > 0 and A[ind - 1] == target) ind -= 1;
            // iterate all the duplicates
            while (ind < A.len and A[ind] == target) : (ind += 1) {
                // if its unique then true
                if (ind != i and ind != j) return true;
            }
        }
    }
    return false;
}
#+end_src

** Problem 2
The second algorithm does some tricks but for each item of the list it walks the entire remaining list which is equivalent to a twice nested loop so it has \(O(n^2)\) complexity. Here are two better solutions with different trade offs.

#+begin_src zig
/// This soultion reframes the problem. For any valye `i` and `j` chosen where
/// `j < i` you can reverse the value to have the correct assertion `i < j`.
/// Therefore, the problem is really saying to find two unique elements that
/// have the same value. This algorithim use sorts the list before iterating it. 
// After sorting, all the duplicates will be next to each other so any number 
/// that is the same as the next one will satisfy the condition.
/// Complexity: `O(n lg n)`
fn problem2b(A: []usize) bool {
    // edge case
    if (A.len <= 1) return false;

    // sort list
    std.mem.sort(usize, A, {}, std.sort.asc(usize));

    // find duplicates
    for (0..A.len - 2) |i|
        if (A[i] == A[i + 1]) return true;

    return false;
}

/// This meathod uses the same logic but instead uses a hash set to keep track
/// of what elements have been seen. It does however use heap allocations.
/// Complexity: `O(n)`
fn problem2c(A: []usize) !bool {
    var set = std.AutoHashMap(usize, void).init(std.heap.c_allocator);
    defer set.deinit();

    for (A) |v| {
        if (set.get(v) != null) return true;
        try set.put(v, {});
    }

    return false;
}
#+end_src
