#+TITLE: Im From Poem
#+Meta: English 3 (11th grade)
#+AUTHOR: Evan Stokdyk

I am from the stovetop, the sink and the slight sting of sodium stearate.
I am from rice and beans, from Steve and John.
From morning pancakes and
	the silence
	after a storm of people. (5)

I am from being broken, battered or
	my brother's.
I am from hand-me-down clothes and
	do-it-later metalities.

I am from white shirts and tattered shoes, (10)
	from skateboarding with sand between my toes,
	silently cruising down the beach.
I am from calloused hands and bruised knees.
I am from tumbled down the hill,
no one stopped my roll,  (15)
then and even now.

I am from vague mantras and silent stares.
From the abandoned rusted scooter,
	left behind by time,
to a land of depressed gutters, brown grass, (20)
	and a broken street lamp.

I am from This world,
one I did not choose,
but one that treats me kind. (24)

* Analysis
What truth does the language of your poem reveal about your identity?

	In my poem, I chose to create a theme of silence and abandonment which in the context of the ending reveals that my childhood has concluded. 	I first used specific imagery through out the poem to convey my central motif. Two examples of this are the "abandoned scoter" and "vague mantras". I use these to convey the theme of being left behind by time and misguided respectively. However, a hold great nostalgia for playing with that scooter and listen to my grandpas stories and this contradiction is a running idea in this poem that is clairfied by the ending.  Next, I chose to use word chose to convey my theme through the poem. One example of this is the use of silence in line 4 as it takes up the whole line. The storm of people referenced in the next line is repersentative of a morning in my house,  but now that the storm is passed I am just left in silence to remember the what was so great about the storm. The word "silently" is used to a similar effect in line 12, however another example of word choice conveying information is the line "broken, battered or my brother's" in line 6.  This line describes some of my prized possessions in a negative light; despite them being so important in the past they have all either broken or been taken by my brother leaving me with a few things I can hang on my wall to remeber when I used to have so much fun with them. Finally, I closed with references to my childhood to relate back to the central them.  I had a very enjoyable childhood but I think it is over at this point so I wanted to use events and objects from my childhood to convey this. Specificly, lines 10 to 16 convey this very well as the create a somber tone by describing an activity that is often considered fun, walking on the beach, in a pessimistic way. Another example of this same concept is in line 2 where I mention the names of the two men who have had the largest  impact on my life, however by have them be paired along side rice and beans which is generally consider a bland dish also conveys them in that light.  These choices work together create a theme throughout the poem of contradicting good moment with somber connotation to narrates that the good time of the past are now in the past.
