:PROPERTIES:
:ID: 7E5CCF06-B940-4836-9274-4E7E89A46E88
:END:
#+title: A Deal for Two (Story)

* Notes
hippies bc why not
No one knows why they are in this mess and noone has the guts to pull the trigger.
Occurs in the 70s just pre-internet. If things go right then the story will be long but if everything goes right then it will be shorter. Revenge Story, People with egos. Three guys work together to steal one of their cars back that got reoposesed. Pride passion and social presure.

* Story

#+begin_quote
- Evan Stokdyk
- English - Block 4
- Crime Essay
- A Deal for Two
#+end_quote

"I hate it when they do that. It's like they're trying to chastise
me or something," Dexter spouted. "It's like they think I'm some
idiot or something, I'll tell you if you put me in the same room,
well I would show thei... well, I -- it's just."

"Go on, finish that, don't go on getting shy now!" Leroy chirped
back. Detexter was glowing now with a hatred inside him he couldn't
divulge.

In fact, the whole city was glowing tonight. Despite the long shadow
over the city, a light seemed to spill out from cracks. The sky was
pure black or were those just clouds? It didn't matter as it all was
the same from the ground and stars were just things you learned about
in school.

Leroy thought he was an honest man but just kept getting unlucky. He
had spent more time "between jobs" than at jobs. But he wasn't out of
a job. That was for the vagrant and shiftless people of the world.
When he was out of a job, it wasn't his fault, he had just grown sick
of his old boss. He knew he could do better for himself and refused to
put up with what people gave him. Who was his old boss again? He knew
he needed him for a referral but couldn't remember. No matter. That
was a job for a much less tired him. He was a man of impulse and right
now he was growing tired of Dexter's nonsensical rant.

"They think they're better than me. Like, some fancy ass writer
strings words together and then hops on their high horse talking about
metaphors and irony. It's aaall garbage and they just think that we
eat that up. Like even the word, even the word author. Auuthoor. Such
a refined pretentious word, that has to be the perfect irony for these
smartass fools. Even when you get their words they don't mean any more
than what's on the page," Dexter decreed.

As he spoke he shifted his weight back and forth as if any moment he
was going to take flight. His feet dangling over the edge kicked and
flayed as his knotted hair waved in and out of face. Impulsively he
took a sip from the paper cup next to him. The straw in his mouth, the
logical conclusion to someone emulating his long spider-like fingers.
He looked like a light breeze could knock him over. His long face
seemed to carry an ever present morbid look that would not leave him
out of place wearing a suit selling sleeping pills or wearing nothing
sleeping under a bridge. For now he was working at a lawn care rental
shop and at night he was always "busy" with no alibi as to where he
went. He clearly wasn't sleeping as eyes had fallen about halfway down
his face from a lack of it. Currently, they darted around like a
scared animal looking for anything to point his anger to as he peered
back at the road below the auto shop the three sat atop a headlight
appeared at the end of the road.

” -- is that it?” Dexter asked, steadying his sway.

The third figure looked up as if waking from hibernation. His eyes
squinted down at the road beneath heavy eyebrows. There was silence
for a moment as they waited for the glare from the headlights to die.

"No. Don't you have anything else to talk about other than your own
incompetence," he said, his voice drawn out slow like molasse.

"You clearly gotta start paying more attention because that's not
what I'm saying, Marco. The problem is that I either always get it or
never get it. There is the literal meaning that anyone who reads can
get and then there is this made up fake second meaning," Dexter said
with much more composure than before.

"Inspiring ...," jested Marco.

"Hey, I'd love to hear an opinion from you and not be more
patronizing. Show us how good you are with words," Dexter said
sharply.

"If you talk about that dumb ass burger place again I'll push you off
this damn roof," Leroy exhumed.

"You annoy me so much, I know you don't have the guts so why don't
you pretend to be nicer," Marco replied.

"You can pretend I'm nicer real easy, all you have to do is smile!
And that tip is free."

"Fuck you."

"Gross."

"Fine, here's your dumb story. I was at the library trying to figure
out how anyone desires any of these laws, because I was trying to go
fishing on the weekend and had no clue about this permits stuff. I was
waiting in line at the library. They must have had coupons in the
market yesterday because I felt like I was backed up to the other side
of the building. It's so crazy that they are trying to send people
out where some guy comes in with his dog and they kick him out. Like
sure it's no dogs inside but I have seen about half a dozen people in
their before with .."

"Wait, when was this?" asked Dexter.

"Uh, like 12 -- Thursday. Anyway they got like some goons set up at
the door trying to stop the festival that's slowly forming at the
library right now when this woman just walks by them. With her she got
some real big bird with her on a leash. This thing is bigger than her,
like a real wild animal."

"Hold up, I saw you at 12 on Thursday."

"Yeah, it's a fake story. I don't know birds, but this thing had
dinosaur legs and talons to match. They stopped her and told her that
there's no pets in here and she's like 'oh no this is a service
animal'. At that exact moment the bird looks me right in the eye and
just lets out a booming squawk. Like insanely loud and shrill --"

"Wait a minute, why?"

"Do you want to here the res-- ."

"Why would you make up a fake story?"

"Because you wanted me to tell you something poetic."

"Damn, you really do not get it."

"You two are a joke," laughed Leroy.

The flash of another headlight blinded them. Another moment of
silence.

"Nope, still not it." said Marco.

"No really, explain it, I want to know," Dexter tried.

"Once you know how the trick is done it ruins it forever."

"Tell me Houdini."

 "You were talking about how everything in books is fake and dinosaurs
are fake so I thought I should put the ideas together."

"You really are stupid aren't you."

"No, dinosaurs were made up by museums to sell more tickets to their
bone displays."

"I can't believe you made up that whole story for such a dumb joke."

Marco's looks rather on the heavy side right now, however that might
as well be irrelevant to him as he is like a shapeshifter. Within days
it's like he could become someone else then drop off the face of the
planet. However, for that to happen he would need to learn how to plan
past the next 30 seconds. For now he works as a plumber, likely
causing more problems than he fixes.

"WHO TOOK MY CAR!" Marco looked to the sky and screamed.

"You got over that quick, what now," asked Leroy.

#+begin_quote
"While I was thinking that this whole stake out thing is kinda a waste
of time and we could just ask and see if anybody knows," said Marco
with a grin on his face.
#+end_quote

#+begin_quote
"You were three months behind, the dealer took it you oaf."  said
Leroy growing more confused.
#+end_quote

#+begin_quote
"I was only two and was still getting it. They just need to learn
patience."
#+end_quote

#+begin_quote
"I'm still mad," said Marco.
#+end_quote

#+begin_quote
"Hey, hey get over it Leroy has a true story to tell you."
#+end_quote

#+begin_quote
"I do?" asked Leroy.
#+end_quote

#+begin_quote
"Yeah, I'm bored and I expect you to fix that," said Dexter.
#+end_quote

"Well I'll try. You see, my uncle was a jewel thief, of course he denies
it now but if you get him in private he might tell you. He told me about
this time he had to get into the crazy mansion. It was some loner, no
one ever showed up and all the people who worked there had been there
for like 20 years or something crazy. So how does he get in, well first
he shows up as surveyors and says that there is fracking deep within
some caves that run deep underground the house. Any normal person says
that and they are sent out of there immediately but how does he get it
from? He has a canary. People say that you can get anywhere with a
ladder, but if you have a canary, well. Nobody on the whole planet knows
any better and if it seems like you do then they just let you in. Once
he is past the gate he's got tes of eyes on him if he ever moves
towards the house. There's no chance he gets anywhere close to the
place."

#+begin_quote
A third pair of headlights, or rather just a single headlight causes
Leroy to stop.
#+end_quote

"Yep that's it, up we go," proclaimed Marco.

The three of them stood up from their ledge above the auto shop and
walked back across the other side of the roof now talking about the car.
They descend the side ladder down part way and jump down the next floor.
From around the back they can see the pull into the garage but it stops
out of view.

"Come on. Let's go around."

The city lights on the street seem to paint a spotlight on the three.
They keep walking around. As they round the corner the auto shop comes
into view with the familiar low hum emanating from it.

“Let's head in here, " Marco said with a flick of his head towards a
burger place next to them. 

"What happened? Did all that grease finally make its way to your
brain? You have finally lost it. You're seconds away from your car and
you stop now?" said Dexter.

"I ain't that crazy, it's just they're not ready yet. The guy showed
up 30 seconds ago. He is still in there stretching his old legs. Name
a mechanic who has ever taken less than 30 minutes?" said Marco.

Dexter looked at Leroy who with a shrug said "he's not /even/ wrong."

"But just saying, if you get me in there for 20 bucks an hour and I
would have it done in 5," said Dexter.

"Ok, desperado," said Marco.

"Just come eat with fatso here," said Leroy.

They all walk up to the back of the line, talking about more random
whims. Dexter talks about a shoemaker with a foot fetishes and they
pay for their food.

Eventually the conversation returns to Leroy's uncle and he continues
his story, "so what does he do now, he just goes home. Just walk to
the back fence. Hops it and leaves for the night. No one can contact
him or even have a clue where he is while he is enjoying a nice nap,
everyone else is wondering if he is ok. The next night he comes back
with one of those really bright lights spotlighting himself the whole
time as he walks up to the house from the outside. Says likely the
dumbest thing ever to the people at the front about how the cave leads
far underground. He then asks to test the water and let him in. Oh
yeah he covered himself in oil and all that to sell it. He just goes
up to the bathroom and pulls out a lighter and turns on the water. He
tells the person watching him that there might be a dangerous amount
of gas in these rooms and so the person naturally leaves to tell
others. That gives him like 5 minutes alone and he is good so ..."

From the front register a commotion at the register. Someone is
shouting incoherently, the words sound almost foreign yet the emotion
comes out clear.

"Cold Turkey. I think that's our queue. We don't want to deal with
too much crazy tonight."

They emerge back out into the city, the fresh air a relief from the
cramped diner. They group up, a team huddle, and Marco starts
planning: "Ok, Dexter you are a prospective buyer who just happened to
see the car pull in from your apartment across the street. You were so
blown away that you called us here to inspect it immediately. You play
offense, just keep whoever is in there busy, engaged, whatever, just
not focused on us. Leroy, you are helping me find the keys. They
should keep it somewhere in the back," said Marco.

"How do you expect me to help you, give you some luck."

"No. I make my own luck. Just do uh -- something. Alright? And
remember, once you go in. Never. Break. Character."

The trio walks down the street as the light of the show grows closer.
Each set makes the hum of a radio more audible. A stout mechanic is on
one knee looking at the yellow lights at the front of the car. When
the three fools enter the shop they can clearly see that it is just
him and the car. No one else. Perfect. The shop smells of grease oil
and sandwiches made from both. The dim light in the room and bright
moon makes it seem as if more light is coming from the gray concrete
floor than the roof. 

(gaslighting begins)

Dexter starts talking, gaslighting him. In time Marco and Leroy manage
to make their way around the shop picking things up like they are
walking around a candy store. Not finding the keys. Dexter is talking
with the mechanic in an effort to learn more about who has the car as a
very much background focus thing

(searching)

"I've just got one more question ..." 3 more cabinets. "... tell me
..." 2 more pushed over a broken lock. ".. When you got this car ..."
Locker smashed over and a sink broke. ” .. who was the owner?”

One final cabinet opened to reveal a rack of keys hanging on the
inside, as the two friends in the back scanned the keys they listened
to the timid mechanic's response.

"Yes, that's what I've really been trying to say is that the person
who owns this car is", his mouth kept moving but no words were heard.
Yet everyone knew who he was talking of the name that brought fear
before it was even said. This terrifies the group and so they start to
give up and seem to panic. 

They see a boot land on the top stair, and A single shot comes from
above as then the figure stands still. Time stops with him as well.
The characters have just enough time to figure out what has happened
as they are then running towards the car.  One broken window later the
car is on and speeding out of there. As they leave Dexter croaks out,
"You done making that luck yet?" Marco panics as Leroy drives away. He
has clearly fallen from grace.

(pandemonium)

"What happened to you uncle?"

".. yeah he got caught you know, 5 minutes ain't enough for anyone."

(reflection)

Leroy managed to pour out from his closed mouth: "He's not dead,
Marco, he only got shot in the leg. Say it with me, he's not dead."
The lights were gone but the sound remained yet all too vague to
discern a gun's shot from a bird's squawk.
