:PROPERTIES:
:ID: BEBD3471-745A-4135-B2D9-A3777731AA1F
:END:
#+title: Christan Reflection Paper

Q: compare christianity in the middle east and south asia

* Reflection
christianity has developed differently accross the world. This is most evident
in poeple veiw of the character Jesus. His message remains the same but the
optics change accross locations. both had very early and sucsessful encultures
saw with christianity. MAKE A CLAIM.

First, For the middle east it was the birthplace of Christ and
in south asia the aremians established churches for diasporas. Before western
arrival, the religon existed in some SA regions (SOURCE NEEDED). However, the
middle east would soon have the invention of Islam and south asia always
contended with hindism. later each region would have a renewed evangalization
attempt. In ME it would be the roman Catholic church but they were ass. Later,
Christianity was mostly brought to India by the Catholic Spanish and the
Protistant Portuguese.

Second, Each of these cultures, due to their different dominat religon has a differing
understanding of what god means. This changes the way indigenization, or the
process of interaction with local culture language and rituals, is done in each region.

Islam: God Transcendent
Christianity: God incarnate
Hindu: God anthropomorphsized

Avatar
decends into the world to restore order (hindu)
people of shiva dont belive in avatars of god
human liberation, free from opression
god decends to restore humanity
jesus suffers human temptation

divine order, restore rightousness

Hindu: 3rd largest religon in the world, largest back in 52CE
St. Thomas went to India in 52CE
Hindu and christans supported each other

liberation theology: in india, opposition to the caste system and sati

guru - teacher who instead has students seek them out

someone who walks the spiritual path
give advice based on their own life
grow on a spirtiyal level
both human and divine, connect to people and god the same

jesus as a pilgrame - he moves
kigdom of god - collective, resonates with asian cultur

active teacher
parables - samilar

sikhism - also have a guru

*** ME - God understanding
too many sects, minor disagrements

Different understant of god in Islam and christanity.
In mosques there are no images of gods or divine figures.

Many persian (iraqi) christans started out as jewish
there adoptions was what wrote much of the origonal literature

Greek orthodox, seperation of christ as a divine and human figure rather than
both, this spread to asian shores - Many population that disagreed were considered heritics of the west (copts in egypt + syrians) - refusal to call mary mother of god

In 1099, frankish crusaders brought latic christianity to the middle east. This
was done after the easter skizim which caused many oriental priest to be more
lienient to these territories and coop more. The Maronites even submitted to
the pope while perserving some of its traditions.

in the 11th and 14th centry many christological disscussions where put aside as
they didnt want to call the other side heretics anymore. This allowed for new
relationships between middle eastern groups. This relationships were often
advocated for as cooperation rather than submission which was not liked by Rome.

In the 14th centry, many of the churches would be destroied by the turkish
mongols. This caused a large decrease in numbers. This got worse in 1516 when
they were conquered by the ottomans and taxed.

*** Muslim Rule
Initally, the collapse of persian empire boarders was good as it allowed more
freedom of movement. Many poeple moved east to Uzbekistan Afghanistan and china

christans had some freedom of workship and organization under "dhimma", also
legall systems. In exchange they had to pay taxes, keep a low porfile, wear
specific glothing and accept the islamic state. In someplaces this was lienient
and in other it was far from it.

Often times they would translate greek texts to Syriac and Arabic. Later, in the
Abbasid perdiod around 1200 they engaged in idological disguessions about why they each
held their beliefs.

Around 16th to 18th centry, there would be a growing feeling of other felt
between middle east christans and islam due to a growing european precents.
This cause less contanct.

During the "Arab Awakening" Christan and Muslims world once again work together
against the Ottomans and renewal of the arabic language. This was very common
after the first world war.

** Failed colonialism
*** SA - Mission
Portuguese arrived in late 15th centry mostly in sir lanka to set up ports
start of 17th centry settements were formed in Bangladesh

protugeuese arrived to find some already Christan communities from syria. - help in Syriac: "Hindu in cultur, Christian in religin and oriental in worship" - these broken off to form Syrian Orthodx church in India

Goa: city that became center of south asian Christianity

some early 17th centry protistant translated the bible and preached in the
langageu of the people rather than forcing them to learn engligh (unlike the
Anglicist)

*** SA - Instituitional Churches
In the mid 19th centry the churches became intritutionalized. This means they
had more capicity to control labor. Most common was educational things. - "civilizing mission", building schools, mostly target at high cast poeple - to preach gospel, the people need to be civilized - aslso some formed care instituitions, overall viewed as nation-building

*** SA - Colonalism
Often times relationships with the local rules was important. Colonalist would
try to ally with existing rulers.

East india company forbid missionaries as this could upset the locals and
indanger the company.

caste system is long pervasive in south asia. Christans value equality for all
as so it was a non starter for them in principal. In practice, they often just
adopted it and professed the missionaries as high caste.

failed indigenization to the caste system

Finnally, each religon has a different way of appealing to people

*** SA - Appeal
Dalit mean untouchable, the lowest caste

Majority of Chrstians in south asia today. british rule and industrialization
made put many of these laborors out of a job. Some joined the british army and
others turned to christianity for a new identity. Similar in Pakistan.

Some churches oppossed mass conversion on the idea that individual was better
or that too many low caste people would drive away the high class.

People in central india would convert with hopes of being liberated. More
tribal or natural socienties in northeast india and bangladesh converted as
well.

Much of the conversion was done under the duress of colonization and caused a
reactionary movement to stop conversion.

The struggle with integration as they are in tension from being seen as foriegn
beacuse rulers were from christan nations. Many laws today have sperate
contingencies for christans relating to marriage and inheritance. Becoming a
christan required giving up your place in society so many would form ghettos.

Christians are a minority in south asia. But, the exists all over the sub
continent which shows the attempts made and the underlying appeal.

In the middle east there is no explicit way that it trys to adapt to the new
envirorment. This explains why some people belive it will disappear from the
region. However, some people do belive there should be better integration with
islam. There are some poeple who have imigrated to lebanon in modern times.

** Notes
*** SA - How did they become Christians?
- Construction and promotion of education instituitions in the reigon
- Famines leading to need for ___
- Caste system opposition and exitus
- Colonisation imposing certain values
- Historical divisions that were put aside for unity

*** SA - What are the challenges of Christianity in this continent?
- Historically, some ministers were upset with the british colonials protecting
- Nationalist ideas seeing christans as being based in foriegn rule
- Anti-christian sentement rooted in colonial history
- Secular goverments and reliogus wars
- Present day, reservation exclution policies that underrepresented Christans in polotics
- Present day blastphomy laws that restrict practice and religous speach

You will conclude with your own reflection on what you have learned.
