:PROPERTIES:
:ID: 1786BC28-3CB9-46D2-B983-4B96F5BC1ABC
:END:
#+title: Comparing Buddhist Schools

Evan Stokdyk
DUE: 3/2/25
RSOC 86 - Schools of Buddhism Essay
Prof. Colette Walker

Comparing Different Buddhist Schools

Buddhism is a religion based on the life and teachings of Sadartha Guatama combined with other vedic traditions beforehand. These teachings are referred to as the dharma and like all religious script there are many different ways of interpreting the teachings. Soon after the death of the Buddha, many Buddhist universities and monasteries offered ways for people to critically engage with and converse about these teachings. From these various different sects were created, with the 3 main ones being Theravada, Mahayana and Varjanda. In addition, Buddhism remains a constantly amended tradition so many new teachings from more current figures are brought in and combined with existing understandings to create a more full doctrine. Overall, the buddhist endeavor is partially an academic one that aims to guide people to nirvana, an escape from rebirth, peace or “blowing out”, through various different methods.

The major Buddhist schools are Theravada (or Hinayana), Mahayana and Vajrayana. Each of them agree on the fundamental teaching that avoiding dukkha, or suffering, leads to a better life. However, not performing one set of actions leaves a lot of other possibilities and this room from interpretation. Each of these schools have filled this in with different practices, rituals and ideas.

One important difference between each school of thought is their history in how they came to be.The Theravada school is the oldest and therefore the closest to the direct teachings of buddha. It maintains this by being the most conservative branch, rarely adopting new beliefs. It was mainly seen in many Buddhist institutions in India before the Mongol invasion. Today it remains mostly in South Asia but has a small population of practitioners. It focuses on the core teachings of the Buddha being the four noble truths, the eightfold path and the three refuges alongside the writings in the Pali canon. It mostly came to popularity after being adopted by the Mauryan emperor, Ashoka.

Mahayana was born out of many thought leaders in these buddhist institutions who wanted to see a faster track to enlightenment based on the beliefs that the dharma from the age of the buddha had died down. It takes the same teachings seen in Theravada schools but adds many more writings from the Prajnaparamita, perfection of wisdom series. Today it is common in east and southeast asia but has also been exported to some areas in the western world. Similarly to Theravada, it gained much of its popularity from the support of Chinese and Vietnamese kings.

Finally, Vajrayana (or Tantric Buddhism) is the most recent and most progressive school in that they adopt many teachings to keep up to date with the changing world. It is very similar to Mahayana but yet again aims to offer a faster but less convenient path to enlightenment. It is very popular across Central Asia and Sri Lanka and similarly is popularized by Royal powers in Tebet and Sri Lanka.

Next, much of the practice of each sect is very different in each of their efforts to reach enlightenment. Each one has some sort of ritual surrounding focusing on the elimination of suffering. Theravada exists with the longest time frame and thus places emphasis on the six realms of rebirth and accumulations of good will in life. In this path, Theravada buddhists attempt to live the most pure life today in hopes of a reward in the next life.

Mahayana buddhist believe in pure lands that allow the faithful to have an easier path to enlightenment. This faith is particularly different as there is no parallel to other schools. Many people will chant the name of Amitabha/Amida who is said to be the great creator of the pure land Sukhavati. In other schools within the sect, there is a focus meditation like in Chan/Zen, where one focuses on breathing and the teachings of the Heart and Lotus Sutra.

Vajrayana builds again on Mahayana and introduces the idea that nirvana can be achieved in life, not just after death. As a result, much of their teachings speak about sudden enlightenment where a devotee can see the whole truth in a given movement. One way they practice this is through sand mandala meditation in which an elaborate art piece is constructed with sand and then destroyed shortly after to signify the temporary nature of all things.

When comparing the different sects, there is a clear one way relationship with the beliefs of each. Vajrayana agrees with almost all of Mahayana but adds a few new things which do not contradict but rather undermine its teachings. Both of them however are very different from Theravada. It is possible that a member of Vajrayana could plan to achieve enlightenment over many cycles of samsara, but someone in Theravada would not seek rebirth into a pure land.

Moreover, the schools disagree on what happens after enlightenment. In Theravada, someone who will not reincarnate ever again is called an Arhat and they are expected to keep their good practice until they die so they can reach a higher realm of nirvana. Majayana, however teaches the Bodhisattva bodhisattva path of someone who is enlightened and could escape the cycle of samsara but instead of reaching nirvana now stays in the human realm to lead others to it as well. Similarly, Vajrayana speaks of yogis who in fact are enlightened in this life and act as great teachers to lead others to enlightenment. Overall, across the different schools there are various ways of expressing the same ideas each that see people taking different steps towards the ultimate goal of liberation from suffering.
