:PROPERTIES:
:ID: 87A82830-8751-4222-8EE5-1641ABA642C7
:END:
#+title: Famine & Fasting

Evan Stokdyk\\
Due: 6/11/25\\
ENGL 157 - Prof. Dasgupta

/How does media coverage of famine and fasting affect the way people react and challenge the national image? How have different images on non-eating shaped colonial history and national image?/

How Spectacle Changes Memory: Famine and Fasting in the Image of South Asia

The idea of starving to death is justifiable scary, to wither and die over a long period of time evokes a primal fear that doesn't comfort anyone. Although the modern era makes food distribution easier and famine less likely, the fear remains. The idea of someone leaving this comfort and choosing to go through a painful process seems even worse. These fears are often reflected in the media that we consume and the way people react and remember events is influenced by this media. The main story of World War Two covers European battles and the rest of the world was considered secondary, but in fact these were not side stages but other peoples main story. They consist of peoples whole lives and to marginalize them as such is a disservice. The image of famine in India built upon this media. Image covers not just imagination but what it looks like as famine is shown in photos. This fear of famine is used in the mythos of South Asia and has framed it as a nation of strife. This paper will look at this image that has been created by famines and the ways it changed how South Asia reacts to challenges in their national image.

The role of fasting is seen as resistance to colonialism. The history of political resistance in India shows the glaring effect of fasting, as there are many examples of what it looked like before and after. These ideas have often been explored in the past. Much of this has been covered by past research which leads to these two basic conclusions: 1) famine was caused by the British and 2) fasting is resistance to the British. These can seem like parallel ideas but upon closer inspection they represent a large dichotomy in the lives of people and the reduction of agency and choice. The roles of each are very different in addition to the separate causes. I will show how these are used in different situations interchangeably and their effects. Prior literature has shown the way the British rule used India as an industrial base to move undesirable industry far away but this paper will examine how these actions are viewed in the national image. Global coverage of famine in South Asia is sparse and often frames events as coincidental whereas fasting is seen as a venerated way of religious resistance. People who suffer from famine are not the same as those who record it which causes skewed foreign memories of tragedy. Fasting is often placed at the forefront of this era's resistance to imperialism but this paper will examine what causes voluntary non-eating to be widely publicized compared to its counterpart. By looking at the way South Asians depict famine in the media the vision can be compared to reality to see opinion which reveals that media capture under the British has had negative consequences on national image. Fasting shows a break from this system as it remains well known despite political repression. Overall, famine being used as a tool has led to people over associating with resistance measures rather than the harm caused.

--------------

Famine is clearly bad and no one wants to cause it, yet it remains despite innovations and industrialisation, it continues to happen. Famine was capable of aiding the British which is seen in a quote from Amartya Sen, a great Indian economist, who talks about the reasons colonialism could supply itself. He says that “European leaders could begin constructing supply networks within the borders of their own states without worrying whether slaves thousands of miles away were well fed or not” (Sen 1981, 221). Famine in this way is a form of imperialism as it keeps nations from developing their own agency outside of the role of a vassal state to feed the home. Famine acts as an extension of British political violence in addition to normal systems of repression. In the present, the consequences of losing this became obvious with the British revaluing their currency in 1967 among other things. The true value of this is not to cause harm as no one gains from that but rather to export existing harm to another nation. They aimed to profit from the Indians and a hungry population can still be abused. The profound change in industrialization of Europe was not people not having to farm but being able to export food from India. This all added entropy to the system which resulted in small problems becoming larger problems.

During the Bengal Famine of 1943, “prohibition of export of cereals in general and of rice in particular from each province, which had come into operation during 1942 with the consent of the government of India prevented the price spiral in Bengal being broken by imports from the other provinces” (Sen 1981, 77). There was an opportunity to prevent the suffering but shortages were caused partially by weather and mostly by British intervention to use rail lines to bring food out of the nation. Therefore it was not constructed out of malice but rather simple profit. Additionally, “all the famines which have occurred in Russia from 971-1970 can predominantly be attributed to human factors” (vien Dando 1976, 219). Although a different nation, it is still applicable in this situation due to similar economic factors. Together these illuminate an abuse cycle that helps to explain how these events can occur as it is not malice but rather attempting maximum exploitation and flying too close to the sun. It is a collection of bad people, not a single orchestrated action. These make it much harder to blame a single person or organization for the famine. As such, reporting on it becomes rather stale and non engaging. Upon the British requesting that things not be published, there is minimal resistance as the potential gain of defecting has the minimal upside of producing a headline simply stating that grain supplies are 10% lower than reported. Finally, famine is never a goal but rather a consequence, therefore it always coincides with another world event which allows it the ability to take the back stage.

Fasting, however, takes center stage in each moment it is present because of its shock value described previously. Fasting as a form of resistance is based on religious freedom and civil disobedience and specifically in this era, resistance to British rule. The reasons people undertake a fast are often interesting and sometimes can be perverted for ill gain. It takes advantage of its particular visceral reaction to seeing one slowly die to make change.

Fasting, notably it always breaks a moment of solace so it can take center stage. Gandhi had a medical team to support his fasts which does not evoke the separatist resistance vision. Prison hunger strikes however are one of the few tools present for these powerless people with no other option left. It gives them a vast public reach due to its easily understood nature. It was as such used in prison strikes where people had “With the protest fast, Gandhi enlarged the scope of the traditional spiritual fast, recasting its purpose as a public demonstration of spiritual self-discipline and also, by his own example, rousing his followers' ethical consciousness to forsake violence as a means to political independence” (Shah 2022, 110). It is described this way as a very calculated endeavor as well as leaning partially into its religious roots. In the plight of hunger, the natural response is not to plan a hunger strike and so when it is something it is orchestrated. Each person has no desire to overshadow a tragedy but collectively the accessibility and virality results in more coverage.

--------------

Understanding the opinion of people involves looking at the media they create to see their truth. This gives a better understanding and view into a time period by reflecting on the way they react well as the consequences and their reflections. The primary source relevant to famine and fasting is the 1981 Bengali movie In Search of Famine. It follows a fictional movie troupe and their efforts to produce a film set during the Bengali famine. They enter into a town to file and the way they talk and interact with ideas and conflicts presented throughout ultimately illuminates their overall ignorance of consequences. At the end of the film history rhymes with striking workers forcing the production to leave showing that they are not naive but rather just fail to understand how the past can confront the present. The film covers the Bengali Famine over 35 years after the events. The main characters suffer greatly and are repeatedly offered to have their land bought out. They refuse for the entire movie and we watch as his strife becomes real in both the film and present (Sandhane 1981, 45:12). The locals better understand which results in much of the conflict in the latter half.

One way the movie revises history is their vision of martyrdom. The script is written in the film world and the actors proclaim: “We starve for days but he won't sell the land. // I remember those days. I've seen people like that. We were better off, then” (Sandhane 1981, 30:05). This is said in film so it is meant to be how the film crew reflects on the famine, as opposed to the real human creators of the picture. The film crew illuminates how they get their depiction of the famine wrong in this moment as it paints these people in civil defiance and longing to return to that moment. This is indicative of framing that is common not just around famine but any large scale global tragedy. The people in it are often more concerned with their own survival. This takes the history of known resistance martyrdom in fasting and falsely applies it here. These rewriting of facts are quite common as “those directly affected by calamitous hunger or famine scarcely possess the strength or leisure to put down in writing what they are suffering” (Agrawal 2000, 108). The way these were often recorded was through British newspapers which would often be requested to withhold information.

One scene that helps to identify the way the image is foreign to even the people in the movie, the experts, is the game the characters play part way through the movie. They attempt to identify the different famines based on a picture and fail a considerable amount (Sandhane 1981, 50:02). Not only does this raise their mission to document the famine into question, but shows this is a consequence of revisionism with many of them being younger than the event they aim to cover.

The best description comes directly out of the movie which is when it asks “Have you seen the famine? Of course not, that was a long time ago” (Sandhane 1981, 1:11:00). This best describes it as people move on from things they did not experience. The way this cycle is broken is through education which is why the perseverance of resistance acts is greater. This differs from the way we view the scene in Brotherless Night where in that book K's, a militia freedom fighter, fast is compared to Ghandis despite a 30 year difference (Ganeshananthan, 247). This shows the zeitgeist that these resistive moments can live in where despite the less than perfect goal of K within the book a comparison is drawn to an extremely different context.

There is no chain of consequence between fasting and famine as even long before Gandhi was fasting in 1918, he would write about Indian home rules in the Hind Swaraj (1909). This sets it far before the defining famine at the end of the British rule. This is why the media must be controlled. To supply people with news of a failure like this would cause others to question the minimal supposed help of being under British crown rulership for the other colonies.

--------------

Overall, I believe that spectacle plays a large role in shaping the memory and images of history. Not only due to its immediate impact on those who see or hear it but the virality of the media it produces. This is seen in the way that the history of fasting largely overshadows the history of famine even in In Search of Famine.

It can be tempting to reduce complex ideas to singular moments. The idea of fasting is that relatively quickly someone can wither and die within a day compared to famine which involves a long process of malnutrition ultimately followed by an untimely death. The ability to capture this entire process as one idea is hard. In retrospect, the danger and problems are clear but it is hard to see the damage of something that works so slowly in the moment. British controlled news coverage did not need much persuasion to ignore this lamentful process as seen from Amartya Sen's excellent book again about how “the values of ‘shortages' were recalculated [higher] specifically for Bengal for the period until the next crop” (Sen 1981, 82). This data about food stores is what is used to predict whether the price will become untenable for people in the near future and so this sort of manipulation can result in death.

Importantly, the role of food in each situation is starkly different. The fundamental difference of choice makes it something that can be taken advantage of. This is seen again in /Brotherless Night/ where K's climactic fight of resistance is instead characterized with the author's description that the whole crowd was “Like him, some of them were also performers and opportunists” (Ganeshananthan, 253). Although this may be an over characterization, the way people can use fasting as a way of creating attention is not to be underestimated. Yet someone who is incapable of affording food cannot step out of this role. This power dynamic represents another aspect of repression of the voice of those who suffered famine. After all, a single death is a tragedy and a million deaths are a statistic.

Lastly, the British also understood the way that accessible revolutionary actions could harm their rule. “British administrators worried that the strategy of hunger strikes ... would travel across the empire” (Shah 2022, 112). This national mobilization often takes time and creating a rallying cry is a powerful ability. It is no surprise that the British showed fear against this practice as “at the conclusion of his fast the government arrested Gandhi. He was convicted of sedition” (Shah 2022, 115).

Understanding the way viral and misinformation was used in the past can help us better understand today what these effects are in the modern world. Overall, there is a significant gap in understanding of famine versus reality both within and outside the nation. This is significant because it shows the way state media can bury skeletons of the past by venerating solutions to their own problems.

*Bibliography*

Agrawal, Arun. “Agrarian Environments” Duke University Press, 2000. Ananthamurthy, U. R. 1976. Samskara : A Rite for a Dead Man. Delhi: Oxford University Press.

Dando, W. A. “Man‐made Famines: Some Geographical Insights from an Exploratory Study of a Millennium of Russian Famines.”. Ecology of Food and Nutrition 4, 1976.

Gandhi, Mahatma, and Anthony Parel. Hind Swaraj and Other Writings. Cambridge ; New York: Cambridge University Press, 1997. Ganeshananthan, V. V.. Brotherless Night. India: Penguin Books, 2023.

Newman, Lucile F., and William C. Crossgrove. Hunger in History: Food Shortage, Poverty, and Deprivation. Cambridge, Mass., USA: B. Blackwell, 1990.

Sandhane, Aakaler. “আকােলর সন্ধােন (In Search of Famine). YouTube, January 7, 2019. https://youtu.be/SRZqN-b0VpM.

Sen, Amartya. Poverty and Famines: An Essay on Entitlement and Deprivation. Oxford : New York: Clarendon Press ; Oxford University Press, 1981.

Shah, Nayan. “Gandhi's Fasts, Prisoner Hunger Strikes, and Indian Independence.” In Refusal to Eat: A Century of Prison Hunger Strikes, 1st ed., 110--32. University of California Press, 2022. https://doi.org/10.2307/j.ctv20dsb1j.10.
