:PROPERTIES:
:ID: C641461E-3F9A-46BF-89F6-76C4B3DE1E0C
:END:
#+title: Plight of the Blights (Essay)
#+filetags: :todo:

--------------

** date: "2024-06-12"
* Final Essay
Evan Stokdyk
6/12/2024
Leither - 3:30 MW
English 3 - Essay 3

Plight of the Blights

"Appropriate time? The first I knew about it was when a workman arrived at my home yesterday. I asked him if he'd come to clean the windows and he said no he'd come to demolish the house." - Arthur Dent, Hitchhiker's Guide to the Galaxy

Time passes, buildings age and replacement is needed. Nothing lasts forever and so it must be replaced. Rapid urban development can result in buildings out of date with modern building codes. Simply, burgeoning cities result in out of date structures.
Naturally, these degraded buildings could be upgraded in a number of ways. The most popular option in the 50s and 60s was a process called urban renewal. Urban renewal song to invest money into inner cities to restore housing. However, urban renewal did not happen equitably and often was a net negative to the community. This phenomenon can be viewed from a number of different perspectives and time periods. The city, before the destruction, desired to expand its economic reach. The town, during the destruction, sought the ability to practice personal economic freedom and build social fabric. Finally, the government, after the destruction, sought societal benefit and whose funding made it all possible. Examining each of their perspectives signals new reasoning behind why urban renewal was the preferred option.
Charles Abrams, who in 1965 was serving as president of the committee against discrimination in housing, took $25,000 from Ford Foundation to write the book The City Is The Frontier that argues that urban renewal should not be graded on its flaws but rather how it can improve and its ability for slum and blighted area clearance (Abrams, 155). In the first half of the book he harshly says that houses should not be destroyed during a housing crisis. Then, in a monumental tone shift, eases up significantly on the idea (Commentary Bk). He argues then that cities were built in a rush of poor people in the past so that they can be rebuilt now with the automobile in mind such as widening roads and building freeways (Abrams, 157). Urban freeways specifically are mentioned as ways to quickly get people to dense shopping areas in the inner city (Abrams, 157).
However, the story of the city of Rondo, a city in St. Paul, shows how the vision of slums in need of a savior was hallucinated. Urban renewal was often used to erase what existed rather than rebuild. In the 50s, the neighborhood of Rondo was vibrant; it was hard to go more than a block without seeing a thriving business or amenable people. Rondo was the center of a burgeoning music culture; it allowed new stars to rise up in the Minneapolis scene. This created a culture that investmed and supported local stars. Every night, it embodied the 50s idealistic fantasy of live music, parties and friends. Resident Herman Jones describes Rondo like a tight knit community based on family in an interview (Swesson, 22).
Despite the blossoming urban fabric, by 1955 a freeway had been in planning for 6 years. The construction was approved in 1953 yet residents would only hear of its existence in 1955. There was no opportunity to voice their opinions during the planning stage, or rather no one thought it prudent to ask them. Despite this, Rondo citizens attempted to form local groups to resist the demolition. One year later, the Federal Interstate Highway Act would be passed providing the funding Minnesota needed to justify continuing despite local opposition. This resulted in their homes and businesses, primary assets for many families, being severely devalued and then bought below rate. The route was chosen over an alternative that would have been routed outside the density of the city and used empty and low occupancy land (Swesson, 31). It would however have been slightly longer.
The shorter route was chosen. As a direct result of this choice "one in eight African Americans in St. Paul lost a home to I-94. Many black-owned businesses, such as barbershops and movie theaters, were lost and never replaced. Of the homes demolished, 72 percent had been homes to African Americans" (Cavanaugh, 16). Urban renewal is indicative of the type of systemic lie that was prolific in the before the civil rights act. Dr. King even stated in April 27, 1967 that "I see no more dangerous development than the build-up of central cities surrounded by white suburbs". Urban freeways dismantle people and their value added is less than what they provide. Saint Paul admitted their damage to Rondo by road construction yet knew it was wrong for much longer. In fact, despite understanding the flaws, St. Paul continued urban renewal plans, disregarding the voices of the marginalized, revealing a systemic pattern of racism under the moniker of progress. Although urban renewal claimed to lift the poor out of metropolitan vestiges, Rondo was thriving and urban renewal instead acted as a tool to segregate, destroy and control while its creators lied to themselves with shortsightedness and racism to justify its persistence.
Evidence of highways' ability to inhabilitate an area has long existed yet, cities proceeded anyway. Investments in highways were often counterproductive, "I recently learned of a city where $30 million was paid for an urban renewal project. But instead of getting better, the physical condition of the target neighborhood actually got worse" (Nixon, 165). This talks about the surrounding ideas where homes are rebuilt. This was often used to gentrify areas. Community is something that is shared among people and connects them. The story of motivation can be seen in reverse in the story of Rondo. St. Paul began planning and approved a large motor project before receiving any federal funding. The funding only served as added motivation to squash local resistance, not as a reason to itself.
In addition, to build massive infrastructure requires massive resolve. However, the source is initially unclear as in its later years it could be seen to fade. The most public facing address a president does, the State of the Union, President Nixon uses to admit the flaws of urban freeways promising to designate a "portion of the Highway Trust Fund for capital improvements in urban public transportation, including improvements in bus and rapid rail systems. Changing the way we use the Highway Trust Fund should be one of the top items on our national agenda" (Nixon, 166-167). This 1973 address is interesting as it appears to be the sunset of urban interstate freeways. It contains the admission that there are better transport methods in urban areas that don't need the same land resources to operate. Yet despite this speech and policy change, urban renewal continued for 20 additional years. Therefore, it is reasonable to conclude that there exists something other than strictly financial motivation.
Freeways are also argued to provide economic benefit (Abrams, 166-167). This can be examined by a similar project in St. Paul to the I-94 that happened prior. This should have been used as something to study as construction resulted in the neighborhood of Near North being “sliced in half by the construction of the Olson Memorial Highway, which heavily impacted the economic viability of many of the area's corner stores and businesses” (Swensson, 39). Yet they did not use this as an example of what a minor road widening would result in. This shows that there exists an idea of urban renewal and its funding; without the funding, it will continue to happen. President Nixon may have ended urban renewal on a federal level but the idea still lingered on motivated by something. There must exist another motivation for building these freeways.
Urban renewal is a practice that was sunsetted yet continued as it was not based on reason but rather racism. This is indicative of an emotional self lie that Airely details where people can act against logic even if it is harmful (Ariely). And, people act against their best interests all the time, yet in this case they were not consulted which is different. There was a need to convince people who were not interested for the planners. In fact, there exists a guide for exactly this, passing projects despite widespread disapproval. In a shocking lack of empathy, it says that "in none of the cases studied did significant participation on the part of the really lower classes occur. Rather, those persons appeared to be reconciled to a fearful anticipation of bad consequences and to remain helpless" (Kovak, 370). Planners use historical racial inequities to help them to gain support for policies. It shows their willingness to undermine the voiceless in society. As a result, "the average black [Rondo] citizen was rendered invisible in day-to-day city life due to increasing segregation, white flight to the suburbs, and urban renewal" (Swensson, 39). This is a real example of marginalization. St. Paul then apologized for their error, serving as its admission of self lies it maintained to justify the demolition of Rondo (Foxx, 15:03). The acknowledging of harm implicates its deceit and confronts historical mishaps to move towards genuine reconciliation.
These actions are attempted to be justified with research: "After studying several cities I found that it was too early to speak of one city typifying the problems faced be all cities ... I therefore came to the conclusion that I should have to use an imaginary city with many characteristic common to most cities facing problem of urban renewal. In this way we would gain be constructing a mode that would be more representative of the average situation than any single real city" (Doxiadis, 84). This is indicative of the whole culture as all that matters is results, black people out of cities. The reasons can be made up because if you create a model based on what you think will happen then all you will observe is what you expect to happen.
Cities have been ruined by roads. People lie to aid their own world view, even if it is not based on fact. This story is not unique and can be seen in many other cities such as Jefferson St (Nashville), San Juan Hill (New York), Greenwood District (Tulsa) and Brooklyn (Charlotte). With this level of systemic forces, it is easy to feel helpless. Nixon weighs into this as "Perhaps the most important factor in the crisis mentality of the 1960's was the growing sense on the part of the average individual that the circumstances of his life were increasingly beyond his control. Nothing is more important in improving our communities than giving people a sense of control again, letting them know that they can make a difference in shaping the places where they live." (Nixon, 167) This shows a shift in views as in the past the community was explicitly undervalued and not seen as a city asset.
Urban renewal was a method to advance the interests of the powerful at the expense of the poor (Appler). This purpose was mostly to oppress the minority black population within inner cities. The myth spun by Abrams is a pervasive one. However, it is important to recognize that that book contains many contradictory opinions. People choose to live where they do mostly because of the people around it "Demolition of a functioning neighborhood nullifies these choices, disrupts associations and institutions, destroys what the people have added to the neighborhood and attributes that drew them to it in the first place" (Abrams, 315). Moving people from the slums to the suburbs is the equivalent of "let them eat cake". If people can't afford to live in what people have labeled a slum, why would they be able to live in a house.
All of this still leaves the question of who profits from being the racists and the people who sell the cars that drive where people used to live. This resonates more in the modern age as we still see people acting based on racism or financial motivations when they are meant to support the masses.

Bibliography
Abrams, Charles. "The City Is the Frontier". New York. Harper and Row, 1965.

Appler, D. R. (2017). Changing the Scale of Analysis for Urban Renewal Research: Small Cities, the State of Kentucky, and the 1974 Urban Renewal Directory. Journal of Planning History, 16(3), 200-221. https://doi.org/10.1177/1538513216657006.

Ariely, Dan. The (Honest) Truth about Dishonesty : How We Lie to Everyone--Especially Ourselves. New York, Harper Perennial, 2013.

Cavanaugh, Patricia. “Politics and Freeways: Building the Twin Cities Interstate System.” Prepared for Center for Urban and Regional Affairs (CURA) and Center for Transportation Studies (CTS) at the University of Minnesota, October 2006. https://conservancy.umn.edu/items/08857c39-f75e-4452-94b5-912856b9d2d2.

Commentary Bk, “The City Is the Frontier, by Charles Abrams.” Commentary Magazine, 1 Mar. 1966, https://www.commentary.org/articles/commentary-bk/the-city-is-the-frontier-by-charles-abrams/. Accessed 11 June 2024.

Doxiadis, C. A. “Problems of Urban Renewal.” Ekistics, vol. 72, no. 430/435, 2005, pp. 83--100. JSTOR, http://www.jstor.org/stable/43619509. Accessed 5 June 2024.

Foxx, Anthony. “Secretary Foxx Discusses a Transportation Plan for the 21st Century.” YouTube, 15 Dec. 2016, https://youtu.be/QqtJgWaU0zM. Accessed 8 June 2024.

Keeler, Jane D. “The Nurse and Urban Renewal.” The American Journal of Nursing, vol. 65, no. 2, 1965, pp. 90--93. JSTOR, https://doi.org/10.2307/3453071. Accessed 5 June 2024.

Kovak, Richard M. “Urban Renewal Controversies.” Public Administration Review, vol. 32, no. 4, 1972, pp. 359--72. JSTOR, https://doi.org/10.2307/975000. Accessed 5 June 2024.

Nixon, Richard M. "Radio Address About the State of the Union Message on Community Development.". Primary Sources in U.S. Presidential History, March 4, 1973. https://advance-lexis-com.libproxy.scu.edu/api/document?collection=news&id=urn:contentItem:47DJ-HKK0-01K9-023P-00000-00&context=1516831. Accessed June 5, 2024.

Swensson, Andeea. Got to Be Something Here: The Rise of the Minneapolis Sound. University of Minnesota Press, 2017. JSTOR, https://doi.org/10.5749/j.ctt1pwt6k2. Accessed 5 June 2024.

References
Adams, Douglas. The Hitchhiker's Guide to the Galaxy. Harmony Books, 1980.

Milner, Iman. "Future of Black-Owned Coffee Shop is Bright Thanks to Rondo Community Land Trust." Black Enterprise (Online) 2023 Sep 12 2023/09/12/ProQuest. https://www.proquest.com/diversity/docview/2863885883/D2B5D1F9904D43FBPQ/1?accountid=13679&sourcetype=Magazines. 5 June 2024.

van der Hoff, P. T., and George S. Duggar. “URBAN RENEWAL.” Ekistics, vol. 8, no. 48, 1959, pp. 275--84. JSTOR, http://www.jstor.org/stable/43613328. Accessed 5 June 2024.

Volante, Alisha. (2015). The Rondo Neighborhood & African American History in St. Paul, MN: 1900s to Current. Retrieved from the University of Minnesota Digital Conservancy, http://hdl.handle.net/11299/178547.

Wedge, E. Bruce. “The Concept ‘Urban Renewal.'” The Phylon Quarterly, vol. 19, no. 1, 1958, pp. 55--60. JSTOR, https://doi.org/10.2307/273004. Accessed 11 June 2024.

* Sources
Abrams, Charles. "The City Is the Frontier". New York. Harper and Row, 1965.

Adams, Douglas. The Hitchhiker's Guide to the Galaxy. Harmony Books, 1980.

Appler, D. R. (2017). Changing the Scale of Analysis for Urban Renewal
Research: Small Cities, the State of Kentucky, and the 1974 Urban Renewal
Directory. Journal of Planning History, 16(3), 200-221.
https://doi.org/10.1177/1538513216657006

Doxiadis, C. A. “Problems of Urban Renewal.” Ekistics, vol. 72, no. 430/435,
2005, pp. 83--100. JSTOR, http://www.jstor.org/stable/43619509. Accessed 5 June 2024.

Foxx, Anthony. “Secretary Foxx Discusses a Transportation Plan for the 21st
Century.” YouTube, 15 Dec. 2016, https://youtu.be/QqtJgWaU0zM. Accessed 8 June 2024.

Kovak, Richard M. “Urban Renewal Controversies.” Public Administration
Review, vol. 32, no. 4, 1972, pp. 359--72. JSTOR,
https://doi.org/10.2307/975000. Accessed 5 June 2024.

Nixon, Richard M. "Radio Address About the State of the Union Message on
Community Development.". Primary Sources in U.S. Presidential History, March 4, 1973.
https://advance-lexis-com.libproxy.scu.edu/api/document?collection=news&id=urn:contentItem:47DJ-HKK0-01K9-023P-00000-00&context=1516831.
Accessed June 5, 2024.

Swensson, Andeea. Got to Be Something Here: The Rise of the Minneapolis Sound.
University of Minnesota Press, 2017. JSTOR,
https://doi.org/10.5749/j.ctt1pwt6k2. Accessed 5 June 2024.

** #todo Nurse and Urban Renewal
[[https://www.jstor.org/stable/3453071][Link]] - 1965

Written in 1965, offerers a critical examination of urban renewal talking about
how although it does offer some improvements for people it more often is not
even doing what is says all the time (building houses) and that uprooting
families is bad.

Having to move when already struggling can take a hold on health forcing bad
things. Even when you dont have a personal community, you still have a resource
and service community which you are displaced from (not to mention it is
destroyed)

Overall, I think this is a great source I should take the time to read all of
(i have only read the first page)

*** Citation
Keeler, Jane D. “The Nurse and Urban Renewal.” The American Journal of
Nursing, vol. 65, no. 2, 1965, pp. 90--93. JSTOR,
https://doi.org/10.2307/3453071. Accessed 5 June 2024.

* Unused Sources
Volante, Alisha. (2015). The Rondo Neighborhood & African American History in
St. Paul, MN: 1900s to Current. Retrieved from the University of Minnesota
Digital Conservancy, http://hdl.handle.net/11299/178547.

** The Concept Urban Renewal
This is a black journal. i dont know what to make of this as it is very
indicative of the times but from the wrong voice

*** Quotes
"The term - born only in 1954 - means many things to many people. For municipal
offi- cials and taxpayers it means a way of replacing outmoded, worn-out and
blighted areas with sound, well-planned development geared to modern needs; an
answer to the age-old problem of how to reduce municipal expenses and improve
the outlook for increased municipal revenues. For the families living in bad
housing it means a chance for children - our future citizens - to grow up in
decent housing and pleasant neigh- borhoods. For home builders, building supply
dealers, real estate brokers and mortgage bankers it means a new and unlimited
opportunity for neighborhood development, home construction and rehabilitation.
For other interests, the improvement and stabilization of values in central
city districts - now problem areas - represent a most encouraging factor." (Wedge, 55-56)

*** Citation
Wedge, E. Bruce. “The Concept ‘Urban Renewal.'” The Phylon Quarterly, vol.
19, no. 1, 1958, pp. 55--60. JSTOR, https://doi.org/10.2307/273004. Accessed 11
June 2024.

** Black-Owned Coffee Shop
[[https://www.proquest.com/diversity/docview/2863885883/D2B5D1F9904D43FBPQ/1?accountid=13679&sourcetype=Magazines][Link]] - 2023

Not Scholarly

*** Quote
"restore Rondo's uprooted Black middle-class community, which succumbed to the
construction of Interstate 94 in the 1960s" (Milner)

"When I was a young girl, Rondo was a place of Black innovation, abundance, and
joy --- and I am fiercely committed to rebuilding the more than 300 businesses
and 700 homes that were taken from our families,” said Mikeya Griffin,
executive director of the Rondo Community Land Trust" (Milner)

*** Citation
Milner, Iman. "Future of Black-Owned Coffee Shop is Bright Thanks to Rondo
Community Land Trust." Black Enterprise (Online) 2023 Sep 12
2023/09/12/ProQuest. 5 June 2024 .

** Land Use Efficiency in an Urban Renewal
[[https://ascelibrary-org.libproxy.scu.edu/doi/10.1061/JUPDDM.UPENG-4523][Link]]

- land usage in china

** Sustainability of Urban Renewal Projects
[[https://doi-org.libproxy.scu.edu/10.1061/%28ASCE%29UP.1943-5444.0000493][Link]]

Talks about how modern urban renewal works in turkey how it is being used for more sustainable projects

I can use this as a modern comparison as now when they tear down homes they build more.

** Urban Renewal
[[https://www.jstor.org/stable/43613328][Link]] - 1959

- explains logic of UR
- ends saying bulldoze everything

*** Citation
van der Hoff, P. T., and George S. Duggar. “URBAN RENEWAL.” Ekistics, vol. 8, no. 48, 1959, pp. 275--84. JSTOR, http://www.jstor.org/stable/43613328. Accessed 5 June 2024.

** The Rondo Neighborhood & African American History
[[https://web.archive.org/web/20200721015050/https://conservancy.umn.edu/handle/11299/178547#?][Link]] - 2015

Contains links to many other sources but has not information of its own. Is not scholarly but is published.

*** Footnotes
“Renewal Program for Saint Paul.” Saint Paul, Minn: Housing and Redevelopment Authority of the City of Saint Paul, 1959. Minnesota Historical Society.

*** Citation
** The City Is the Frontier (Editorial)
[[https://www.jstor.org/stable/20371823][Link]]

*** Citation
S. M. E. “The City Is the Frontier.” The Phi Delta Kappan, vol. 48, no. 7,
1967, pp. 305--305. JSTOR, http://www.jstor.org/stable/20371823. Accessed 10
June 2024.

** Urban Renewal: Two Views
https://www.commentary.org/articles/commentary-bk/the-city-is-the-frontier-by-charles-abrams/
An annonymus response to the artivle The City is a Frontier that details the
way in which it seems to have a tone shift about half way through. The first
half in ve

*** Quotes
"In 1960 the Ford Foundation made grants of $25,000 each to ten authorities on
housing and planning, in order to induce them to set down their thoughts on
urban renewal. One of the ten was Charles Abrams, a former chairman of the New
York State Rent Commission and the State Commission Against Discrimination, and
now the chairman of the city planning department of Columbia University. The
City is the Frontier is his report" (Commentary, 1)

*** Citation
Commentary Bk, “The City Is the Frontier, by Charles Abrams.” Commentary Magazine, 1 Mar.
1966,
https://www.commentary.org/articles/commentary-bk/the-city-is-the-frontier-by-charles-abrams/.
Accessed 11 June 2024.

* Notes
** Links
- https://en.wikipedia.org/wiki/Rondo_neighborhood
- https://advance-lexis-com.libproxy.scu.edu/api/permalink/1e25fdcf-6f34-4916-bb2a-4bcc94125d88/?context=1516831
