:PROPERTIES:
:ID: 7C35AA49-37A9-4C6B-A202-A6CC1C62DA6F
:END:
#+title: Rough Draft Essay 2

Evan Stokdyk
Due: 10/25/2023
Rough Draft Essay 2
Engl 1a 3:30 - Leither

/Food as Communication/

On average, Americans spend 71 minutes traveling and commuting each day. As a consequence, I have noticed that they are common subjects of complaint for many people. This makes sense as when time within each day is limited, it makes sense to want the most out of everything you do. We spend around 67 minutes per day eating and it possesses many of the same problems that make driving bad. For example, eating fast food is often a solemn experience because it is often done in silence or alone. Despite these similarities, the experience of eating food is not held to the same scrutiny as traffic. Of course, you can go with someone to a sit down restaurant and talk but that happens just about as often as people decide to carpool, 1 in 10. A much better solution is a type of eating that is centered around a social experience, street food.

There are however some reasons to not eat street food over sit down or fast food. The first of which is outlined by a BMC Health journal, which states that in many places of the world street food is not subject to the same regulations as regular restaurants. This can result in less healthy dining experience. Belay Desye, a professor of Environmental Health, says that this unsanitary street food can be a major factor in the transmitter of foodborne illnesses especially in low and middle income areas. These two experts illustrate the dangers of street food and why it should be avoided when possible in developed areas where there are viable alternatives.

Despite this, street food can actually have more profound impacts than just the food. This is because it can act as a way to unite people through a shared sense of community and culture. It also gives a lens for outsiders of that culture to better understand, join or contribute to its growth because it doesn't hide any information. Its informal nature lends itself to being a way for its makers to represent themselves when they would not normally have the opportunity to. These benefits outway the supposed dangers of street food making it not just important in the developing world, but also in our local communities. Overall, street food offers benefits that traditional restaurants lack for both the makers and the purchasers.

Street food acts as a way to unite people through a shared sense of community and culture. Many cultural ideas and representations born out of the way street food interacts with the world. Street food is often traditional cultural food because the "growing urban population is often the result of continued rural-urban migration and the background of these urban migrants may influence the street food on offer" (Vignola & Oosterveer, 2022). When people migrate from rural areas to the cities they bring their unique world perspectives with them which helps to make more diverse societies. This can help unite the rural urban divide within a nation by allowing them to communicate in a way other words to help with building understanding within a culture. Street food offers cheap food for people near to where they work and live, importantly cutting travel expenses. However, this cheapness is not the only draw as "out-of-home cooking in the Congo concerns the poor as well as the wealthiest city dwellers" (Jeaheng, 2023). So not only does it provide access to fresh food, it is able to cause interaction between people who would normally live separately. This also illustrates that it is enjoyed by people who have the means of an alternative showing that the people who interact with it daily have made the risk assessment that it is safe to consume. This is great for public health as despite the low price, street food still manages to provide healthy food because "in the streets, traditional drinks are more popular than industrial drinks" (Bouafou & Beugré, 2021). This supports the community by keeping money within the local economy instead of moving it to some large international company. It can also provide new opportunities for work as the supply chain of these vendors is very local. This relates back to the mixing of socioeconomic classes as the people who are usually employing people talk with those who usually need jobs allowing for people to find opportunities more easily. This also can improve community feeling as the feeling of being a part of the making of something is nice. Overall, this shows a vested interest in the community around street food, due to their hesitance to externalize or outsource work outside of that community.

Street food also gives a lens for outsiders to one of these communities to better understand it because of its open nature. This can be seen in the rise of Gastronomy Tourism which has resulted in "street food has received increasing popularity with its combination of local delights and the cultural value of the destination" (Jeaheng, 2023). Many of these gastrointestinal tourists travel to foreign areas just to explore the food. This tourism can bring increased interest in a culture. This new attention is often good as it can push people out of their local bubble of understanding. It is important to acknowledge that tourism is not always great for culture as adding monetary incentives to anything can result in adverse side effects of ignoring tradition to be more appealing and profitable to foreigners. When handled correctly, an increase in tourism can be great for a culture as it puts it on a larger stage and brings money for its preservation. The ability to communicate while eating the food is central to the street culture as many “adolescents believed that the savory, spicy and oily foods sold by street vendors taste better than home-made foods, as they commonly enjoy the street foods while spending time with their peers and share those foods with each other, reflecting social intimacy and bonding that deploy food taste as a demarcation of peer group membership” (Islam, 2019). This communication extends to the people making the food as they are commonly located in plain view allowing the customers to not only watch but talk with the person making their food. This can yield a more personal understanding of who the culture works rather than generalization that would be taught in a classroom setting, leading to a deeper understanding.

Street food's inherent informal nature lends itself to being a way for people to represent themselves when they would normally not have the opportunity to as all people are equally capable of making street food. In lower income areas of the world many people don't have the opportunity to open their own places. However, this problem is not only in these areas of the world, it also exists around your local community. Many low income people in developed countries don't have the monetary ability to open a brick and mortar restaurant leading to only the wealthy being able to show their local food. This is of course a very poor representation of culture as it is by no means only composed of what the wealthy think. Street food solves this problem through the low barrier of entry to starting it. In my experience, I feel I have been given the opportunity to talk to many people I would otherwise not have been able to from street food. On many of these occasions I have communicated with them in something that is not my native language. This expansion of people I have the opportunity to interact with inherently increases my awareness of different perspectives. In general, it offers a new medium of communication by using a different sense than we normally use, taste. In addition, it offers a new way for people to represent themselves as they get the opportunity to set up their own slice of the world at their stand. I have noticed that "the presence of vendors selling fruits and veggies was found to decrease the presence of competing vendors selling non-nutritious food" (Francis & Brinkley, 2020). I observed this as evolution in my community watched it shift as people work together to support public health. This is because it is well known that fresh food is healthier than processed food and because the food is cooked when you order it, it is about as fresh as possible. The ability of people to work together like this is not possible unless the people who are a part of a community are responsible for feeding it, which is often not the case for fast food. In my experience, I have had many types of food for the first time from street vendors. Without street food, I would have likely never have found these secrets in my community as I would not have interacted with these people without the pretense of street food. It is harder to understand something if you have not experienced it and so this can grant new insight into people through experience.

TODO: CONCLUSION

/Bibliography/
Bouafou, K. , Beugré, G. and Amani, Y. (2021) Street Food around the World: A Review of the Literature. Journal of Service Science and Management, 14, 557-575. doi: 10.4236/jssm.2021.146035.

Francis, K., & Brinkley, C. (2020). Street Food Vending as a Public Health Intervention. Californian Journal of Health Promotion, 18(1), 1-16. https://doi.org/10.32398/cjhp.v18i1.2450

Jeaheng, Yoksamon et al. “Influence of Thai Street Food Quality, Price, and Involvement on Traveler Behavioral Intention: Exploring Cultural Difference (Eastern versus Western).” Psychology research and behavior management vol. 16 223-240. 26 Jan. 2023, doi:10.2147/PRBM.S371806

Islam, Mohammad Redwanul et al. “Sociocultural Influences on Dietary Practices and Physical Activity Behaviors of Rural Adolescents-A Qualitative Exploration.” Nutrients vol. 11,12 2916. 2 Dec. 2019, doi:10.3390/nu11122916

Vignola R and Oosterveer P (2022) Street food environmental sustainability in a urbanizing global south: A social practice perspective. Front. Sustain. Food Syst. 6:910547. doi: 10.3389/fsufs.2022.910547
